/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef ,useEffect} from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  useEffect(() => {
    group.current.position.x = props.position[0];
    group.current.position.y = props.position[1];
    group.current.position.z = props.position[2];
  })
 
  const { nodes, materials } = useGLTF('/turtle.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh material={materials.Material} geometry={nodes.Cube.geometry} />
    </group>
  )
}

useGLTF.preload('/turtle.gltf')
